In [4]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

texts = ["apple orange banana lemon", 
         "grape lime mango"]
vectorize_layer = TextVectorization(
    max_tokens=20,
    output_mode='multi_hot',
    pad_to_max_tokens=True
)
vectorize_layer.adapt(texts)
print(vectorize_layer.get_vocabulary())

output = vectorize_layer(texts)
print(output)
print(output.shape)


['[UNK]', np.str_('orange'), np.str_('mango'), np.str_('lime'), np.str_('lemon'), np.str_('grape'), np.str_('banana'), np.str_('apple')]
tf.Tensor(
[[0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]], shape=(2, 20), dtype=int64)
(2, 20)


In [7]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

# Beispielhafte Eingabesequenz mit Token-IDs (Index-Werte zwischen 0 und 9)
# Batchgröße 2, max_len=4 Tokens pro Beispiel
input_sequences = np.array([
  [1, 2, 3, 4],
  [4, 3, 2, 0]  # 0 als Padding
])

vocab_size = 10
max_len = 4

model = keras.Sequential()
model.add(keras.layers.Input(shape=(max_len,)))
model.add(keras.layers.Embedding(input_dim=vocab_size, output_dim=3, mask_zero=True))
model.add(keras.layers.Flatten())
#model.add(keras.layers.GlobalAveragePooling1D())  # unterstützt Masken
model.add(keras.layers.Dense(1, activation='sigmoid'))



# Modell zusammenfassen (als Übersicht)
model.summary()

# Beispiel Forward Pass: Ausgabe des Embeddings für die Eingabesequenzen
output = model(input_sequences)
print("Model output:")
print(output.numpy())


C:\Users\wug2si\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\layer.py:970: UserWarning: Layer 'flatten_1' (of type Flatten) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 4, 3)           │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43 (172.00 B)

 Trainable params: 43 (172.00 B)

 Non-trainable params: 0 (0.00 B)

Model output:
[[0.5058632]
 [0.505166 ]]


In [9]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Name': ['Anna', 'Ben', 'Clara'],
    'Alter': [25, np.nan, 30],
    'Stadt': ['Berlin', 'Hamburg', np.nan]
})
print(data)
print(data.isnull())
print(data.isnull().any(axis=0))


    Name  Alter    Stadt
0   Anna   25.0   Berlin
1    Ben    NaN  Hamburg
2  Clara   30.0      NaN
    Name  Alter  Stadt
0  False  False  False
1  False   True  False
2  False  False   True
Name     False
Alter     True
Stadt     True
dtype: bool


# text split

In [16]:
a = "03.12.2025"
b=a.split('.')
print(b)
b.reverse()
print(b)
result = '-'.join(b)
print(result)
result.to_numpy()


['03', '12', '2025']
['2025', '12', '03']
2025-12-03


In [18]:
import pandas as pd
import numpy as np

date = np.array([['2025-10-01'], ['2025-10-02'], ['2025-10-03']], dtype='datetime64[D]')
print(date.shape)
date_pd = pd.to_datetime(date[:, 0])

print(date_pd)
print(type(date_pd))


(3, 1)
DatetimeIndex(['2025-10-01', '2025-10-02', '2025-10-03'], dtype='datetime64[s]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


In [27]:
import pandas as pd
import numpy as np
data=[ '2025-10-01', '2025-10-02']
print(data)
data_np = np.array(data)
print(data_np.shape)
data_np= data_np.reshape(-1,1)
print(data_np.shape)

['2025-10-01', '2025-10-02']
(2,)
(2, 1)


# zeilen verschiebung
data[:-forecast_length, 4:] = data[forecast_length:, 4:]

In [30]:
import numpy as np
import pandas as pd

# ---- 1️⃣ Beispiel-Daten ----
# Stell dir vor: 10 Tage Daten mit 6 Spalten
# Spalten: [sales, temp, rain, humidity, public_holiday, weekday]
data = np.arange(10 * 6)
print(data)
data=data.reshape(10,6)
print("Ursprüngliche Daten (erste 10 Zeilen):\n", data)

# Forecast: wir wollen 3 Tage in die Zukunft vorhersagen
forecast_length = 2

# ---- 2️⃣ Feiertags- und Wochentagsspalten verschieben ----
# Wir verschieben ALLE Spalten ab Index 4 um 3 Zeilen nach oben
data[:-forecast_length, 4:] = data[forecast_length:, 4:]

print("\nNach Verschiebung (ab Spalte 4 um 3 Zeilen):\n", data)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
Ursprüngliche Daten (erste 10 Zeilen):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]

Nach Verschiebung (ab Spalte 4 um 3 Zeilen):
 [[ 0  1  2  3 16 17]
 [ 6  7  8  9 22 23]
 [12 13 14 15 28 29]
 [18 19 20 21 34 35]
 [24 25 26 27 40 41]
 [30 31 32 33 46 47]
 [36 37 38 39 52 53]
 [42 43 44 45 58 59]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


In [31]:
for i in range(0, 30, 2):
   print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
