# kern_size=1, stride=1

In [4]:
import torch
import torch.nn as nn

# Einfacher Input: 1x3x4x4 (1 Bild, 3 Kanäle, 4x4 Pixel)
x = torch.arange(48.0).reshape(1, 3, 4, 4)
print("Input (3 Kanäle, 4x4):")
#print(x[:,:,0:2,0:2])  # Erste 2x2 Pixel zeigen
print(x )

conv = nn.Conv2d(3, 3, kernel_size=1)
print("\nGewichte (uninitialisiert):")
#print(conv.weight[0, :, 0, 0])  # Erstes Gewicht zeigen
print(conv.weight)  # Erstes Gewicht zeigen

out = conv(x)
print(f"\nOutput shape: {out.shape}")  # [1, 3, 4, 4] ✓
print("Output erste 2x2 Pixel:")
print(out[:,:,0:2,0:2])


Input (3 Kanäle, 4x4):
tensor([[[[ 0.,  1.],
          [ 4.,  5.]],

         [[16., 17.],
          [20., 21.]],

         [[32., 33.],
          [36., 37.]]]])
tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]]])

Gewichte (uninitialisiert):
Parameter containing:
tensor([[[[-0.2143]],

         [[-0.1387]],

         [[-0.1089]]],


        [[[-0.0899]],

         [[-0.1896]],

         [[-0.0495]]],


        [[[ 0.1527]],

         [[-0.1379]],

         [[ 0.3713]]]], requires_grad=True)

Output shape: torch.Size([1, 3, 4, 4])
Output erste 2x2 Pixel:
tensor([[[[-5.5827, -6.0446],
          [-7.4301, -7.8920]],

         [[-4.7572, -5.0862],
        

# kern_size=1, stride=2 (for downsampling)

In [5]:
import torch
import torch.nn as nn

# Einfacher Input: 1x3x4x4 (1 Bild, 3 Kanäle, 6x6 Pixel)
x = torch.arange(108.0).reshape(1, 3, 6, 6)
print("Input (3 Kanäle, 6x6):")
print(x)  # Erste 2x2 Pixel zeigen

conv = nn.Conv2d(3, 3, kernel_size=1,stride=2)
print("\nGewichte (uninitialisiert):")
#print(conv.weight[0, :, 0, 0])  # Erstes Gewicht zeigen
print(conv.weight)  # Erstes Gewicht zeigen

out = conv(x)
print(f"\nOutput shape: {out.shape}")  # [1, 3, 4, 4] ✓

print(out)

Input (3 Kanäle, 6x6):
tensor([[[[  0.,   1.,   2.,   3.,   4.,   5.],
          [  6.,   7.,   8.,   9.,  10.,  11.],
          [ 12.,  13.,  14.,  15.,  16.,  17.],
          [ 18.,  19.,  20.,  21.,  22.,  23.],
          [ 24.,  25.,  26.,  27.,  28.,  29.],
          [ 30.,  31.,  32.,  33.,  34.,  35.]],

         [[ 36.,  37.,  38.,  39.,  40.,  41.],
          [ 42.,  43.,  44.,  45.,  46.,  47.],
          [ 48.,  49.,  50.,  51.,  52.,  53.],
          [ 54.,  55.,  56.,  57.,  58.,  59.],
          [ 60.,  61.,  62.,  63.,  64.,  65.],
          [ 66.,  67.,  68.,  69.,  70.,  71.]],

         [[ 72.,  73.,  74.,  75.,  76.,  77.],
          [ 78.,  79.,  80.,  81.,  82.,  83.],
          [ 84.,  85.,  86.,  87.,  88.,  89.],
          [ 90.,  91.,  92.,  93.,  94.,  95.],
          [ 96.,  97.,  98.,  99., 100., 101.],
          [102., 103., 104., 105., 106., 107.]]]])

Gewichte (uninitialisiert):
Parameter containing:
tensor([[[[ 0.0112]],

         [[ 0.2535]],

         

# AdaptiveAvgPool2d
Input H=7, Output h=2 → Kernel_size = ceil(7/2) = 4, Stride = floor(7/2)=3

In [11]:
import torch
import torch.nn as nn

# ResNet layer4 Output
x = torch.arange(49.0).reshape(1, 1, 7, 7)  # 1 Kanal, 7×7
print("Input 7×7:")
print(x.squeeze())

pool = nn.AdaptiveAvgPool2d((2, 2))
out = pool(x)
print(f"\nOutput shape: {out.shape}")
print("Output 2×2:")
print(out.squeeze())


Input 7×7:
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12., 13.],
        [14., 15., 16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25., 26., 27.],
        [28., 29., 30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39., 40., 41.],
        [42., 43., 44., 45., 46., 47., 48.]])

Output shape: torch.Size([1, 1, 2, 2])
Output 2×2:
tensor([[12., 15.],
        [33., 36.]])


In [10]:
x = torch.randn(1, 12, 7, 7)      # layer4 Output
out = nn.AdaptiveAvgPool2d((1, 1))(x)              # → [1, 12, 1, 1]
print(out.shape)                   # Bleibt immer 1×1 egal ob 7×7 oder 100×100!
print(out)

torch.Size([1, 12, 1, 1])
tensor([[[[-0.0815]],

         [[-0.0813]],

         [[-0.2798]],

         [[ 0.2187]],

         [[ 0.1289]],

         [[-0.2387]],

         [[ 0.1851]],

         [[ 0.1239]],

         [[ 0.0186]],

         [[-0.1588]],

         [[-0.1076]],

         [[ 0.1040]]]])
