# wei völlig verschiedene Aussagen, die oft vermischt werden

Man muss strikt trennen zwischen:

A) Ordnung existiert
0 < 1 < 2 < 3 < 4

B) Abstände sind gleich
dist(0,1) = dist(1,2) = dist(2,3) = dist(3,4)


👉 A ist ordinal
👉 B ist metrisch

2️⃣ Ist gleicher Abstand bei ordinalen Targets wichtig?
❌ In den meisten realen Problemen: NEIN

Beispiele:

Schulnoten

1 → 2: oft kleiner Unterschied

4 → 5: oft dramatischer Unterschied

Sternebewertungen

4 → 5: Luxus

1 → 2: existenziell

Kreditrating

BBB → BB: massiv

AA → AAA: marginal

👉 Ordnung stimmt, Abstände nicht

3️⃣ Konsequenz für das Modell (sehr wichtig)
❌ Wenn du MSE benutzt

Dann sagst du dem Modell implizit:

„Die Abstände sind gleich und metrisch sinnvoll“

Das ist eine starke Annahme, die fast nie garantiert ist.
✅ Wenn du „y ≥ i?“ benutzt (CORN / cumulative link)

Dann sagst du:

„Ich weiß nur, dass höher > niedriger“

keine Abstände

keine falsche Metrik

nur monotone Ordnung

👉 Das ist die richtige Abstraktion für ordinale Daten

4️⃣ Und wo passt jetzt der OrdinalEncoder für y rein?

Jetzt zur Kernfrage:

Wann ist OrdinalEncoder für y korrekt?

Antwort (präzise):

✔️ OrdinalEncoder ist korrekt, wenn eine echte Ordnung existiert
❌ aber er sagt nichts über Abstände

Der Encoder allein ist neutral.
Die Loss-Funktion entscheidet, ob Abstände wichtig werden.
Der Encoder allein ist neutral.
Die Loss-Funktion entscheidet, ob Abstände wichtig werden.

5️⃣ Kombinationen – was sagen sie wirklich?

- Encoding + Loss,	     Aussage über Abstand,	Empfehlung
- OrdinalEncoder + CE //	 Abstand egal //	         ok, aber Ordnung ungenutzt
- OrdinalEncoder + MSE //	 Abstand gleich//	        ⚠️ meist falsch
- OrdinalEncoder + y≥i + BCE// 	Abstand egal //	⭐ korrekt
- 
👉 Nicht der Encoder ist gefährlich, sondern MSE.

6️⃣ Intuition in einem Satz

Ordnung sagt: „größer / kleiner“.
Abstand sagt: „wie viel größer“.

Ordinale Probleme liefern fast immer nur das Erste.

7️⃣ Wann WÄREN gleiche Abstände wichtig?

Nur wenn du sicher bist, dass:

Klassen aus einem metrischen Messprozess stammen

Schwellen gleichmäßig gesetzt wurden

Differenzen linear interpretierbar sind


8️⃣ Klare Empfehlung (ohne Grauzone)

Ordnung real, Abstand unbekannt → Ordinal (y ≥ i + BCE)

Ordnung real, Abstand garantiert → Regression

Ordnung egal → Klassifikation


In [3]:
import torch

# Beispiel: 5 Klassen (0–4)
y = torch.tensor([0, 1, 2, 3, 4])

def ordinal_targets(y, num_classes):
    return torch.stack([
        (y >= i).float() for i in range(1, num_classes)
    ], dim=1)

y_ord = ordinal_targets(y, num_classes=5)

print("y= [0, 1, 2, 3, 4]:  \n", y_ord)
y = torch.tensor([0, 1, 2, 4])
y_ord = ordinal_targets(y, num_classes=5)
print("y= [0, 1, 2, 4]:  \n", y_ord)

y= [0, 1, 2, 3, 4]:  
 tensor([[0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])
y= [0, 1, 2, 4]:  
 tensor([[0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 1.]])


# A Trainingsmodel for OrdinalEncoder

In [6]:
# Datensatz (synthetisch, aber realistisch)
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(0)

# künstliche Features
X = torch.randn(200, 5)

# latenter Score + Rauschen → ordinale Klassen
latent = X[:, 0] + 0.5 * X[:, 1]
print("latent:\n", latent[0:10])
y = torch.bucketize(
    latent,
    boundaries=torch.tensor([-1.0, -0.2, 0.5, 1.2])
)

print("Target distribution:\n", torch.bincount(y))
print(y.shape)
print("X:\n", X[0:5])
print("y:", y[0:10])

latent:
 tensor([-1.7020,  0.5340,  0.5041, -0.9236, -0.1787, -0.6722,  0.5245,  0.4683,
         0.2939,  1.5678])
Target distribution:
 tensor([29, 53, 47, 40, 31])
torch.Size([200])
X:
 tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487],
        [ 0.6920, -0.3160, -2.1152,  0.3223, -1.2633],
        [ 0.3500,  0.3081,  0.1198,  1.2377,  1.1168],
        [-0.2473, -1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502]])
y: tensor([0, 3, 3, 1, 2, 1, 3, 2, 2, 4])


In [5]:
#Ordinale Targets erzeugen (CORN-Style)
def ordinal_targets(y, num_classes):
    return torch.stack(
        [(y >= i).float() for i in range(1, num_classes)],
        dim=1
    )

num_classes = 5
y_ord = ordinal_targets(y, num_classes)
print(y_ord[:10])

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 1.]])


# model(X) ruft intern die forward()‑Methode deines Modells auf, und model.train() brauchst du nur, wenn du Schichten wie Dropout oder BatchNorm hast.
Was bedeutet model(X)?

OrdinalNet erbt von nn.Module.

In nn.Module ist __call__ überschrieben: Wenn du model(X) schreibst, passiert ungefähr:

model.__call__(X) wird aufgerufen (weil das Objekt „callable“ ist).

__call__ kümmert sich um Hooks, Autograd etc.

Am Ende ruft __call__ deine implementierte forward()‑Methode auf.

Also: output = self.forward(X)

Warum kein model.train()?

    - PyTorch‑Modelle haben zwei Modi:

Train‑Modus: model.train()

    - Dropout ist aktiv, BatchNorm nutzt Batch‑Statistiken und updatet Running Stats.

Eval‑Modus: model.eval()

     - Dropout ist aus, BatchNorm nutzt nur die gespeicherten Running Stats.

Standardmäßig ist ein neues Modell im Train‑Modus, d.h. model.training == True.


In [6]:
#
# CORN-Modell: CORN (Conditional Ordinal Regression for NN)
# 2 NN layers 
# num_classes=5

betw_nn_no = 16  # try with 8
class OrdinalNet(nn.Module):
    def __init__(self, in_features, num_classes):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_features, betw_nn_no),
            #nn.BatchNorm1d(betw_nn_no),  # <-- Batch Norm (nach Linear oder ReLU)
            nn.ReLU(),
            #nn.Dropout(p=0.2),           # <-- Dropout (20% der Neuronen aus)
            nn.Linear(betw_nn_no, num_classes - 1)
        )
    def forward(self, x):  # forward im aktuellen Modus (hier train)
        return self.net(x)  # logits


## model(X) ruft intern die forward()‑Methode deines Modells auf, und model.train() brauchst du nur, wenn du Schichten wie Dropout oder BatchNorm hast.

In [7]:
# Training
# model(X) -> forward()

model = OrdinalNet(5, num_classes)
optimizer = optim.Adam(model.parameters(), lr=0.01)
criterion = nn.BCEWithLogitsLoss()
epoch_n= 120
for epoch in range(1, epoch_n):
    optimizer.zero_grad()
    logits = model(X)
    loss = criterion(logits, y_ord)
    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        #print(logits.shape)
        print(f"Epoch {epoch:3d} | Loss {loss.item():.4f}")


Epoch  20 | Loss 0.4947
Epoch  40 | Loss 0.2935
Epoch  60 | Loss 0.1802
Epoch  80 | Loss 0.1274
Epoch 100 | Loss 0.0983


In [8]:
# Vorhersage → ordinale Klasse
model.eval() # 1. Layer-Verhalten auf "Vorhersage" stellen
with torch.no_grad():
    logits = model(X)
    probs = torch.sigmoid(logits)
    y_pred = (probs > 0.5).sum(dim=1)

print("True:", y[:10])
print("Pred:", y_pred[:10])


True: tensor([0, 3, 3, 1, 2, 1, 3, 2, 2, 4])
Pred: tensor([0, 3, 3, 1, 2, 1, 3, 2, 2, 4])


# Ein anderes Beispiel:

https://www.v7labs.com/blog/cross-entropy-loss-guide


In [9]:

import numpy as np

def softmax(z):
    z = np.array(z)
    exps = np.exp(z)
    return exps / np.sum(exps)

z = [1.0, 2.0, 3.0]
probs = softmax(z)
print(probs)


[0.09003057 0.24472847 0.66524096]


In [10]:
import torch
import torch.nn as nn

logits = torch.tensor([
    [2.0, 0.5, -1.0, -2.0, -3.0],  # Prediction
])

target = torch.tensor([0])  # Note "1"

loss = nn.CrossEntropyLoss()
print(loss(logits, target))


tensor(0.2608)


In [11]:
import torch
import torch.nn.functional as F

logits = torch.tensor([[2.0, 0.5, -1.0, -2.0, -3.0]])
target = torch.tensor([0])
print(target.shape)

probs = F.softmax(logits, dim=1)
print("Softmax:", probs)
print(probs.shape)
print(probs[0, target])
manual_loss = -torch.log(probs[0, target])
print("Manual loss:", manual_loss)

loss = nn.CrossEntropyLoss()
print("PyTorch loss:", loss(logits, target))


torch.Size([1])
Softmax: tensor([[0.7704, 0.1719, 0.0384, 0.0141, 0.0052]])
torch.Size([1, 5])
tensor([0.7704])
Manual loss: tensor([0.2608])
PyTorch loss: tensor(0.2608)
