# Filterformat in torch.tensor und Keras format
kernel_torch.permute(): ja
np.permute(): no


In [5]:
import torch
# two channels:
kernel_torch = torch.tensor([
    # Kanal 0
    [
        [ 1,  0, -1],
        [ 1,  0, -1],
        [ 1,  0, -1],
    ],

    # Kanal 1
    [
        [-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1],
    ]
])

print("kernel_torch.shape:", kernel_torch.shape)

print("kernel_torch:\n", kernel_torch)

kernel_torch.shape: torch.Size([2, 3, 3])
kernel_torch:
 tensor([[[ 1,  0, -1],
         [ 1,  0, -1],
         [ 1,  0, -1]],

        [[-1, -1, -1],
         [ 0,  0,  0],
         [ 1,  1,  1]]])


# convert into keras format

In [7]:
import numpy as np

kernel_keras = kernel_torch.permute(1, 2, 0).numpy()

print("kernel_keras.shape:", kernel_keras.shape)
print(kernel_keras)

kernel_keras.shape: (3, 3, 2)
[[[ 1 -1]
  [ 0 -1]
  [-1 -1]]

 [[ 1  0]
  [ 0  0]
  [-1  0]]

 [[ 1  1]
  [ 0  1]
  [-1  1]]]


In [8]:
import numpy as np

kernel = np.array([
    # Kanal 0
    [
        [ 1,  0, -1],
        [ 1,  0, -1],
        [ 1,  0, -1]
    ],

    # Kanal 1
    [
        [ 0,  1,  0],
        [ 0,  1,  0],
        [ 0,  1,  0]
    ],

    # Kanal 2
    [
        [-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]
    ]
]) 
print("torch format:",kernel.shape)
print(kernel)
kernel_keras= kernel.transpose(1, 2, 0) # 👉 wichtig für Keras-Format
print("Keras format:",kernel_keras.shape)
print(kernel_keras)

torch format: (3, 3, 3)
[[[ 1  0 -1]
  [ 1  0 -1]
  [ 1  0 -1]]

 [[ 0  1  0]
  [ 0  1  0]
  [ 0  1  0]]

 [[-1  0  1]
  [-1  0  1]
  [-1  0  1]]]
Keras format: (3, 3, 3)
[[[ 1  0 -1]
  [ 0  1  0]
  [-1  0  1]]

 [[ 1  0 -1]
  [ 0  1  0]
  [-1  0  1]]

 [[ 1  0 -1]
  [ 0  1  0]
  [-1  0  1]]]


# 3x3x Keras filter

In [30]:
import torch
import numpy as np

# unser vorheriger Keras-Filter (3,3,3)
kernel_keras = np.array([
    [[ 1,  0, -1],
     [ 0,  1,  0],
     [-1,  0,  1]],

    [[ 1,  0, -1],
     [ 0,  1,  0],
     [-1,  0,  1]],

    [[ 1,  0, -1],
     [ 0,  1,  0],
     [-1,  0,  1]],
])

print("kernel_keras:\n", kernel_keras)

kernel_keras:
 [[[ 1  0 -1]
  [ 0  1  0]
  [-1  0  1]]

 [[ 1  0 -1]
  [ 0  1  0]
  [-1  0  1]]

 [[ 1  0 -1]
  [ 0  1  0]
  [-1  0  1]]]


In [31]:
kernel_np= kernel_keras.transpose(1, 2, 0)
print("kernel_np:\n", kernel_np)

kernel_np:
 [[[ 1  1  1]
  [ 0  0  0]
  [-1 -1 -1]]

 [[ 0  0  0]
  [ 1  1  1]
  [ 0  0  0]]

 [[-1 -1 -1]
  [ 0  0  0]
  [ 1  1  1]]]


In [32]:
kernel_torch= torch.tensor(kernel_np)
print("kernel_torch:\n", kernel_torch)

kernel_torch:
 tensor([[[ 1,  1,  1],
         [ 0,  0,  0],
         [-1, -1, -1]],

        [[ 0,  0,  0],
         [ 1,  1,  1],
         [ 0,  0,  0]],

        [[-1, -1, -1],
         [ 0,  0,  0],
         [ 1,  1,  1]]])


# Image-Format für Pytorch
## X= (N, C, H, W)
## Beispiel: 2 images, 3 channels, 9x9 image-size (2,3,9,9)
## images: x = torch.randn(2, 3, 9, 9) 
## filter_kernel:  (1,3,3,3): out_c, in_c, h_filter, w_filter

In [16]:
kernel_np = np.array([
    # Kanal 0
    [
        [ 1,  0, -1],
        [ 1,  0, -1],
        [ 1,  0, -1]
    ],

    # Kanal 1
    [
        [ 0,  1,  0],
        [ 0,  1,  0],
        [ 0,  1,  0]
    ],

    # Kanal 2
    [
        [-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]
    ]
]) 
kernel_torch= torch.tensor(kernel_np)
print("torch format:",kernel_torch.shape)

torch format: torch.Size([3, 3, 3])


In [21]:
import torch.nn as nn

print("kernel_torch.shape:",kernel_torch.shape)
kernel_torch_0=kernel_torch.unsqueeze(0).float() 
print("kernel_torch_0.shape:",kernel_torch_0.shape)
print("kernel_torch_0:\n", kernel_torch_0)

conv = nn.Conv2d(
    in_channels=3,
    out_channels=1,
    kernel_size=3,
    bias=False
)
print("weight.data vor\n", conv.weight.data) #zufällig besetzt
conv.weight.data = kernel_torch_0
print("weight.data nach\n", conv.weight.data)

kernel_torch.shape: torch.Size([3, 3, 3])
kernel_torch_0.shape: torch.Size([1, 3, 3, 3])
kernel_torch_0:
 tensor([[[[ 1.,  0., -1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]],

         [[ 0.,  1.,  0.],
          [ 0.,  1.,  0.],
          [ 0.,  1.,  0.]],

         [[-1.,  0.,  1.],
          [-1.,  0.,  1.],
          [-1.,  0.,  1.]]]])
weight.data vor
 tensor([[[[-0.1583, -0.0845,  0.0522],
          [-0.0551,  0.0694, -0.1705],
          [-0.0231,  0.1396, -0.0821]],

         [[-0.1470,  0.0425,  0.1658],
          [ 0.1346, -0.1017, -0.1090],
          [ 0.0882,  0.0379,  0.1629]],

         [[-0.0207,  0.1179,  0.0055],
          [ 0.1659,  0.1764, -0.0448],
          [-0.0350, -0.0090,  0.1755]]]])
weight.data nach
 tensor([[[[ 1.,  0., -1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]],

         [[ 0.,  1.,  0.],
          [ 0.,  1.,  0.],
          [ 0.,  1.,  0.]],

         [[-1.,  0.,  1.],
          [-1.,  0.,  1.],
          [-1.,  0.,  1.]]]])


In [ ]:
#test bild : Test-Convolution

In [15]:
# Dummy-Input: 2 Bild, 3 Kanäle, 9x9
x = torch.randn(2, 3, 9, 9)

y = conv(x)
print("y-shape:",y.shape)  #  2, 1, 7,7
print(y)

y-shape: torch.Size([2, 1, 7, 7])
tensor([[[[-1.8591,  2.6795, -2.7047,  3.0153, -1.8219, -0.6370, -0.2801],
          [-3.1240,  5.2253, -2.5148, -5.3658,  4.4699,  4.0363, -3.5802],
          [-2.3967,  3.5735, -3.9557, -4.9713,  5.8416,  5.6405, -1.3130],
          [-0.7299,  5.0685, -5.1177, -5.4062,  7.0884,  1.5467, -1.3827],
          [-2.8839, -2.6407, -2.2916,  3.2419,  5.7091, -3.4010, -1.9396],
          [-1.0017, -0.2152, -4.9891, -2.8978,  8.8860, -3.7122,  1.7257],
          [ 2.9615, -3.8628, -5.0206,  1.0146,  7.1714, -3.1222, -0.4628]]],


        [[[ 3.9837,  5.8044,  2.5232, -3.6496, -1.5631, -3.8610, -3.8236],
          [ 8.4270,  2.0053,  0.0748, -5.1306,  0.1782,  0.3457, -3.6203],
          [10.1925,  1.5846, -2.6266, -2.7672,  8.0783, -5.8094, -6.2912],
          [ 4.7809, -1.5220, -0.8279, -2.2587,  7.1509, -4.2800, -5.5001],
          [ 4.5359, -2.2272, -2.0528, -2.2902,  5.0424, -2.5870, -5.3164],
          [ 4.7530, -0.7768, -0.8804, -1.6106, -0.9279,  2.854

# Keras Beispiel: 
## image=: X= (N,H,W, C),  (2,9,9, 3); N=2 images, H=9, W=9, Channel=3
## Keras erwartet: weight= (H, W, in_channels, out_channels) = filter_kernel

In [24]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Sequential
from keras import layers, models


# ------------- Filter (3,3,3) ----------------
# gleiche Zahlen wie vorher
kernel_np = np.array([
    [[ 1,  0, -1],
     [ 0,  1,  0],
     [-1,  0,  1]],

    [[ 1,  0, -1],
     [ 0,  1,  0],
     [-1,  0,  1]],

    [[ 1,  0, -1],
     [ 0,  1,  0],
     [-1,  0,  1]]
], dtype=np.float32)

# Keras erwartet (H, W, in_channels, out_channels)
kernel_keras = kernel_np[:, :, :, np.newaxis]  # add out_channel=1
print("kernel_keras.shape:", kernel_keras.shape)  # -> (3,3,3,1)

# ------------- Dummy Input: 2 Bilder, 9x9, 3 Kanäle ----------------
x_keras = np.random.randn(2, 9, 9, 3).astype(np.float32)
print("x_keras.shape:", x_keras.shape)  # (2,9,9,3)

# ------------- Conv2D Layer ----------------
"""conv = Conv2D(
    filters=1,
    kernel_size=(3,3),
    use_bias=False,
    input_shape=(9,9,3)
)
"""


model = models.Sequential([
    # Die neue, empfohlene Art: Eine explizite Input-Schicht
    layers.Input(shape=(9, 9, 3)),
    
    # Deine Conv2D-Schicht ohne input_shape
    layers.Conv2D(
        filters=1,
        kernel_size=(3, 3),
        use_bias=False
    )
])



# Layer bauen (weights setzen)
# conv.build(x_keras.shape)
# conv.set_weights([kernel_keras])  # list mit 1 Tensor für weight

# ------------- Vorwärtsdurchlauf ----------------
y_keras = model(x_keras)
print("y_keras.shape:", y_keras.shape)  # (2, 7, 7, 1)
print(y_keras.numpy())

kernel_keras.shape: (3, 3, 3, 1)
x_keras.shape: (2, 9, 9, 3)
y_keras.shape: (2, 7, 7, 1)
[[[[ 0.31041557]
   [ 2.4160037 ]
   [-2.1102498 ]
   [ 0.49718612]
   [-1.6240892 ]
   [ 1.5109527 ]
   [-2.2904272 ]]

  [[-2.6071885 ]
   [ 0.5351902 ]
   [-0.21126159]
   [ 0.38543588]
   [ 0.11077818]
   [ 2.1076427 ]
   [-0.6365297 ]]

  [[-1.2457933 ]
   [ 1.7477087 ]
   [-2.4857845 ]
   [ 0.41618457]
   [ 1.695474  ]
   [-0.5056835 ]
   [-2.0971394 ]]

  [[-3.2594724 ]
   [ 0.46126765]
   [-2.70688   ]
   [ 0.25816885]
   [-0.84467036]
   [ 1.6793243 ]
   [-0.38667136]]

  [[-0.19863535]
   [ 0.406673  ]
   [ 1.4569851 ]
   [ 0.26226085]
   [ 0.19112703]
   [ 2.0523517 ]
   [-1.2793078 ]]

  [[ 1.8427463 ]
   [ 0.80693835]
   [-0.78371435]
   [ 0.71775144]
   [-2.7195647 ]
   [-0.7313897 ]
   [-1.41206   ]]

  [[-1.7114749 ]
   [ 1.3580225 ]
   [-1.2322937 ]
   [ 0.11103772]
   [-0.62038994]
   [ 0.707641  ]
   [-2.1830678 ]]]


 [[[-2.1369452 ]
   [ 2.0308743 ]
   [-0.75724775]
   [ 1.7601